# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Document aws-cli

on:
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 获取最新的 tag
      - name: Fetch latest tag
        id: tag
        run: curl -s "https://api.github.com/repos/aws/aws-cli/tags" | echo "latest=$(jq '.[0].name' --raw-output)" >> "$GITHUB_OUTPUT"

      # 拉取 aws-cli
      - name: Clone aws-cli
        run: git clone  --branch ${{ steps.tag.outputs.latest }} --depth=1 https://github.com/aws/aws-cli.git

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # password: ${{ steps.app-token.outputs.token }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: aws-cli.Dockerfile
          push: true
          build-args: SOURCE=./aws-cli
          tags: ghcr.io/${{ github.repository }}:aws-cli-latest
