# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Document numpy

on:
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 拉取 numpy
      - name: Clone numpy
        run: git clone https://github.com/numpy/numpy.git

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # password: ${{ steps.app-token.outputs.token }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: numpy.Dockerfile
          push: true
          build-args: SOURCE=./numpy
          tags: ghcr.io/${{ github.repository }}/numpy:latest
