# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Document python

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Python Version"
        required: true
        default: "3.12"
        type: choice
        # From https://docs.python.org/zh-cn/3.12/_static/switchers.js
        # {"3.14": "dev (3.14)", "3.13": "pre (3.13)", "3.12": "3.12", "3.11": "3.11", "3.10": "3.10", "3.9": "3.9", "3.8": "3.8", "3.7": "3.7", "3.6": "3.6", "3.5": "3.5", "3.4": "3.4", "3.3": "3.3", "3.2": "3.2", "3.1": "3.1", "3.0": "3.0", "2.7": "2.7", "2.6": "2.6"}
        options:
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
          - "3.5"
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
      language:
        description: "Document Language"
        required: true
        default: zh-cn
        type: choice
        # {"en": "English", "es": "Spanish", "fr": "French", "it": "Italian", "ja": "Japanese", "ko": "Korean", "pt-br": "Brazilian Portuguese", "tr": "Turkish", "zh-cn": "Simplified Chinese", "zh-tw": "Traditional Chinese"}
        options:
          - en
          - es
          - fr
          - it
          - ja
          - ko
          - pt-br
          - tr
          - zh-cn
          - zh-tw

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get latest version
        run: echo "VERSION=$(curl https://docs.python.org/zh-cn/3.12/_static/documentation_options.js | grep -o -E [0-9]+\.[0-9]+(\.[0-9]+)?)" >> $GITHUB_ENV

      # 拉取 python document
      - name: Get document
        run: curl https://docs.python.org/${{ github.event.inputs.language }}/${{ github.event.inputs.version }}/archives/python-${{ VERSION }}-docs-html.tar.bz2 | tar -xjf

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # password: ${{ steps.app-token.outputs.token }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: python.Dockerfile
          push: true
          build-args: SOURCE=./python-${{ VERSION }}-docs-html
          tags: ghcr.io/${{ github.repository }}:python-${{ github.event.inputs.language }}-${{ github.event.inputs.version }}
